#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 22 22:24:19 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
