#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 04 02:43:06 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
