#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 03 18:52:31 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
