name = "Ascension of the Technomancer 3"
author = "Lazerous42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bb65a03fcaac1520aabccc8ae3717203e593b4f8a2e7db6a5ebe44413be2f4e"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
