name = "Ascension of the Technomancer 3"
author = "Lazerous42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ea468b085da7715e90c56cc0266947b6d5e507b040d0d4d1a7b5f140c62dd52"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
