name = "Ascension of the Technomancer 3"
author = "Lazerous42"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a16cd002a90f4ce7e213ac9d7d37a1866d2f9d63ac0aeaf8ab0a59d95deeea24"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
